feat: add github actions
open-fabric/openfabric-woocommerce-extension pull request #31
Opened 2023-07-04 05:04 UTC by AbrahamOEd

2023-07-04 06:41 UTC, 0xGosu requested changes

2023-07-04 06:41 UTC, 0xGosu commented on .github/workflows/main.yaml
> +            [ $? -eq 0 ] && make .ci-helper-gh-auto-merge-pr-of-branch
this make cmd helper will not be available here.

2023-07-04 06:42 UTC, AbrahamOEd commented on .github/workflows/main.yaml
> +            [ $? -eq 0 ] && make .ci-helper-gh-auto-merge-pr-of-branch
my bad, just forgot to delete that line as the line underneath does what the make file does

2023-07-04 08:03 UTC, 0xGosu requested changes

2023-07-04 08:03 UTC, 0xGosu commented on .github/workflows/main.yaml
> +        uses: devcontainers/ci@v0.3
there is no devcontainer here, you need to use pure bash run job

2023-07-04 08:24 UTC, 0xGosu requested changes
pls check

2023-07-04 08:28 UTC, 0xGosu requested changes

2023-07-04 08:28 UTC, 0xGosu commented on .github/workflows/main.yaml
> +          password: ${{ secrets.OF_GITHUB_TOKEN }}
remove this

2023-07-04 10:41 UTC, 0xGosu requested changes
pls changes

2023-07-04 10:42 UTC, 0xGosu commented on .github/workflows/main.yaml
> +          gh pr create --head bump/v${new_version} --base $(SOURCE_BRANCH) --fill
pls fix this @AbrahamOEd

2023-07-04 10:42 UTC, 0xGosu commented on .github/workflows/main.yaml
> +        name: Build and run Dev Container task
correct the name pls

2023-07-05 02:12 UTC, 0xGosu approved these changes

2023-07-05 02:13 UTC, merged